name: ali_jaber
description: المصحف كامل بصوت المجود علي جابر.

version: 1.0.0+7

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  http: ^1.0.0
  just_audio: ^0.9.33

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  package_rename: ^1.5.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ali_jaber.jpg"
  min_sdk_android: 21
flutter:

  uses-material-design: true
  assets:
    - assets/images/ali_jaber.jpg
    # - assets/mp3/ # use it only in the offline version
  fonts:
    - family: Amiri
      fonts:
        - asset: fonts/Amiri-Regular.ttf
        - asset: fonts/Amiri-Bold.ttf
 